FROM oven/bun:1

WORKDIR /usr/src/app

ENV DATABSE_URL=""
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/server ./apps/server

RUN bun install
RUN bunx prisma generate --schema=apps/server/prisma/schema.prisma
# RUN bun run db:generate
EXPOSE 8000

CMD ["bun", "run", "dev"]