export const PRE_EXISTING = [
  "package.json",
  "jwt.js",
  "logger.js",
  "database.js",
  "middleware/auth.middleware.js",
  "middleware/error.middleware.js",
];

export const codeMap = {
  "package.json":
    '{\n  "name": "backend",\n  "version": "1.0.0",\n  "description": "",\n  "main": "src/index.js",\n  "scripts": {\n    "start": "node src/index.js",\n    "dev": "nodemon src/index.js",\n    "test": "echo \\"Error: no test specified\\" && exit 1"\n  },\n  "keywords": ["backend","octodock-builder"],\n  "author": "",\n  "license": "ISC",\n  "type": "module",\n  "dependencies": {\n    "axios": "^1.11.0",\n    "bcrypt": "^6.0.0",\n    "bcryptjs": "^3.0.2",\n    "cors": "^2.8.5",\n    "dotenv": "^17.2.1",\n    "express": "^5.1.0",\n    "express-validator": "^7.2.1",\n    "helmet": "^8.1.0",\n    "jsonwebtoken": "^9.0.2",\n    "mongoose": "^8.18.0",\n    "morgan": "^1.10.1"\n  },\n  "devDependencies": {\n    "nodemon": "^3.1.10"\n  }\n}',
  "index.js":
    'import express from "express";\nimport morgan from "morgan";\nimport cors from "cors";\nimport helmet from "helmet";\nimport "dotenv/config";\n\nconst app = express();\napp.use(express.json());\napp.use(cors());\napp.use(morgan("dev"));\napp.use(helmet());\n\napp.get("/", (req, res) => res.json({ message: "Server is UP🚀" }));\n\napp.use(require("./middleware/errorHandler"));\nconst PORT = process.env.PORT || 8000;\napp.listen(PORT, () => {\n  connectDB()\n    .then(() => {\n      console.log(`Server Running on PORT ${PORT}`);\n    })\n    .catch(() => {\n      console.log("encountered an error, re-thinking process .... ");\n      process.exit(1);\n    });\n});\n',
  "routes.js":
    'import express from "express";\nimport authMiddleware from "../middleware/auth.middleware.js";\n\nconst router = express.Router();\nrouter.use(authMiddleware);\n\nexport default router;\n',
  "models.js": 'import mongoose from "mongoose";\n',
  "jwt.js":
    'import { config } from "dotenv";\nimport jwt from "jsonwebtoken";\nimport logger from "./logger.js";\n\nconfig();\n\nconst JWT_SECRET = process.env.JWT_SECRET || "default_secret";\nconst JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || "1h";\n\n/**\n * Generate a JWT for a given payload.\n * @param {Object} payload - Data to encode in the token.\n * @returns {string} Signed JWT.\n */\nexport function generateToken(payload) {\n  try {\n    return jwt.sign(payload, JWT_SECRET, { expiresIn: JWT_EXPIRES_IN });\n  } catch (error) {\n    logger.error("Error generating JWT", error);\n    throw error;\n  }\n}\n\n/**\n * Verify a JWT and return the decoded payload.\n * @param {string} token - JWT string.\n * @returns {Object} Decoded token payload.\n * @throws Will throw an error if verification fails.\n */\nexport function verifyToken(token) {\n  try {\n    return jwt.verify(token, JWT_SECRET);\n  } catch (error) {\n    logger.error("JWT verification failed", error);\n    throw error;\n  }\n}\n',
  "logger.js":
    'import fs from "fs";\nimport path from "path";\nimport { fileURLToPath } from "url";\n\n// Resolve __dirname in ES modules\nconst __filename = fileURLToPath(import.meta.url);\nconst __dirname = path.dirname(__filename);\n\nconst LOG_DIR = path.resolve(__dirname, "../../logs");\nconst LOG_FILE = path.join(LOG_DIR, "application.log");\n\n// Ensure the logs directory exists\nif (!fs.existsSync(LOG_DIR)) {\n  fs.mkdirSync(LOG_DIR, { recursive: true });\n}\n\n// Determine log level from environment (default: info)\nconst LEVELS = { error: 0, warn: 1, info: 2, debug: 3 };\nconst CURRENT_LEVEL = process.env.LOG_LEVEL?.toLowerCase() ?? "info";\nconst CURRENT_LEVEL_VALUE = LEVELS[CURRENT_LEVEL] ?? LEVELS["info"];\n\nfunction formatMessage(level, message) {\n  const timestamp = new Date().toISOString();\n  return `${timestamp} [${level.toUpperCase()}] ${message}\\n`;\n}\n\nfunction writeToFile(formatted) {\n  // Append log entry asynchronously; ignore errors to avoid breaking the app\n  fs.appendFile(LOG_FILE, formatted, (err) => {\n    if (err) {\n      // If file write fails, fallback to console error\n      console.error("Failed to write log to file:", err);\n    }\n  });\n}\n\nfunction log(level, message) {\n  if (LEVELS[level] > CURRENT_LEVEL_VALUE) return;\n  const formatted = formatMessage(\n    level,\n    typeof message === "object" ? JSON.stringify(message) : message\n  );\n  // Console output with colors for better readability\n  switch (level) {\n    case "error":\n      console.error(formatted.trim());\n      break;\n    case "warn":\n      console.warn(formatted.trim());\n      break;\n    case "info":\n      console.info(formatted.trim());\n      break;\n    case "debug":\n      console.debug(formatted.trim());\n      break;\n    default:\n      console.log(formatted.trim());\n  }\n  writeToFile(formatted);\n}\n\nconst logger = {\n  error: (message) => log("error", message),\n  warn: (message) => log("warn", message),\n  info: (message) => log("info", message),\n  debug: (message) => log("debug", message),\n};\n\nexport default logger;\n',
  "database.js":
    'import mongoose from "mongoose";\nimport logger from "../utils/logger.js";\nimport dotenv from "dotenv";\n\ndotenv.config();\n\nconst DB_URI =\n  process.env.MONGODB_URI ||\n  process.env.DB_URI ||\n  "mongodb://localhost:27017/octodock";\n\nmongoose.set("strictQuery", true);\n\nconst connectDB = async () => {\n  try {\n    await mongoose.connect(DB_URI);\n    logger.info("Database connected");\n  } catch (error) {\n    logger.error("Database connection error:", error);\n    process.exit(1);\n  }\n};\n\nexport { connectDB, mongoose as db };\n',
  "middleware/auth.middleware.js":
    'import "dotenv/config";\nimport jwt from "jsonwebtoken";\nimport logger from "../utils/logger.js";\n\n/**\n * Authentication middleware to protect routes.\n * Expects JWT in the Authorization header as: \'Bearer <token>\'.\n * On successful verification, attaches the decoded payload to req.user.\n */\nconst authMiddleware = (req, res, next) => {\n  const authHeader = req.headers["authorization"];\n  if (!authHeader) {\n    logger.warn("Missing Authorization header");\n    return res.status(401).json({ message: "Authorization header missing" });\n  }\n\n  const parts = authHeader.split(" ");\n  if (parts.length !== 2 || parts[0] !== "Bearer") {\n    logger.warn("Malformed Authorization header");\n    return res.status(401).json({ message: "Invalid Authorization format" });\n  }\n\n  const token = parts[1];\n  if (!token) {\n    logger.warn("Token not provided");\n    return res.status(401).json({ message: "Token missing" });\n  }\n\n  try {\n    const secret = process.env.JWT_SECRET;\n    if (!secret) {\n      logger.error("JWT_SECRET is not defined in environment");\n      return res.status(500).json({ message: "Server configuration error" });\n    }\n    const decoded = jwt.verify(token, secret);\n    req.user = decoded;\n    next();\n  } catch (err) {\n    logger.error(`Auth middleware error: ${err.message}`);\n    return res.status(401).json({ message: "Invalid or expired token" });\n  }\n};\n\nexport default authMiddleware;\n',
  "middleware/error.middleware.js":
    'import logger from "../utils/logger.js";\n\nconst errorHandler = (err, req, res, next) => {\n  // Log the error details for debugging and monitoring\n  logger.error(err);\n\n  // Determine appropriate HTTP status code\n  const status = err.status || 500;\n\n  // Provide a generic message for unknown errors\n  const message = err.message || "Internal Server Error";\n\n  // Send JSON error response\n  res.status(status).json({ error: message });\n};\n\nexport default errorHandler;\n',
};
