name: Code Formating
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Install-Dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Event Logging
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Global bun Installation
        run: npm i -g bun
      - name: Format Code Files
        run: npm run format
      - name: Format Code Files using bun
        run: bun run format
