name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy using password auth
        env:
          SSH_PASSWORD: ${{ secrets.password }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no pttl@34.131.170.248 << 'EOF'
            set -e  # stop on error
            cd /octodock
            pwd
            git pull origin main
            bun i
            pm2 list
            pm2 restart 0
            cd apps/client
            pwd
            bun run build
            sudo mkdir -p /var/www/octodock
            sudo cp -r dist/* /var/www/octodock/
            sudo systemctl restart caddy
          EOF
